@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@baseurl = http://{{host}}

GET {{baseurl}}/solarpanels HTTP/1.1

###

GET {{baseurl}}/solarpanels/the%20ridge HTTP/1.1

###

GET {{baseurl}}/solarpanels/the%20ridge/1/1 HTTP/1.1

###

POST {{baseurl}}/solarpanels HTTP/1.1
Content-Type: application/json

{
}

###

POST {{baseurl}}/solarpanels HTTP/1.1
Content-Type: application/json

{
  "section": "Shadow Lands",
  "row": 1,
  "column": 1,
  "yearInstalled": 2000,
  "material": "POLY_SI",
  "isTracking": true
}

###

PUT {{baseurl}}/solarpanels/18 HTTP/1.1
Content-Type: application/json

{
  "id": 18,
  "section": "Shadow Lands",
  "row": 10,
  "column": 10,
  "yearInstalled": 2020,
  "material": "POLY_SI",
  "isTracking": true
}

###

GET {{baseurl}}/solarpanels/shadow%20lands/10/10 HTTP/1.1

###

DELETE {{baseurl}}/solarpanels/shadow%20lands/10/10 HTTP/1.1
