version: "3.7"
services:
    solar-farm:
        image: solar-farm-node
        build:
            context: .
        environment:
            #can't get production env to work at all says error with sequelize
            DEV_ENV: development
            POSTGRES_USER: solar_farm_app
            POSTGRES_PASSWORD: password
            DB_HOST: db
        ports: 
            - "8080:8080"
        depends_on:
            - db 
        #There is something wrong with this script. Probably entering the wrong variables
        
        command: ["./wait-for-it.sh", "db", "npm run db-migrate-seed"]
        #this doesn't belong but will execute in dev enviroment then the container willshut off 
        command: npm run db-migrate-seed
        #this should be triggered automatically (I assume)
        command: npm start
    db:
        image: postgres
        environment:
            POSTGRES_USER: solar_farm_app
            POSTGRES_PASSWORD: password
            POSTGRES_DB: solar_farm  
        ports:
            - '5432:5432'
            
            
